export let tcQuestions = ["What are you esteemed for?", "What are you stress by?", "What is your highest virtue?", "The thing that frustrates me is", "Something I do that may frustrate others is", "You like to receive praise when", "On a bad day, I may", "What stresses me out is"];
export let goldResponses = ["Being Dependable", "Lack of order", "Responsibility", "Lack of planning", "Being bossy and controlling", "Words are used that actually reflect what has been accomplished", "Complain", "Incomplete tasks"];
export let greenResponses = ["Discovering New Insights", "Feeling inadequate", "Objectivity", "Small-talk", "Living in the future", "Specific knowledge you acquired is recognized", "Become overly indecisive", "Lack of control"];
export let blueResponses = ["Being a good listener", "Feeling artificial", "Loyalty", "Violence", "Being passive", "Someone shows praise by a touch on the shoulder", "Fantasize/ Day dream", "Broken promises"];
export let orangeResponses = ["Being fun and taking risks", "Restrictions", "Courage", "The same routine", "Being undisciplined", "Your impact is acknowledged", "Become rude", "Too much responsibility"];
export let hpQuestions = ["Which road tempts you most?", "Do you like to", "What drive do you have?", "What kind of work environment do you like?", "What best describes you?", "What best describes you?", "You enter an enchanted garden. What would you be most curious to examine first?", "What kind of instrument most pleases your ear?" ];
export let ravenclawResponses = ["The cobbled street lined with ancient buildings", "Analyze", "Drive to learn", "I like to work alone and have time to get it right", "Contemplative", "Analytical", "The silver leafed tree bearing golden apples", "piano"];
export let slytherinResponses = ["The narrow, dark, lantern-lit alley", "Strategize", "Drive to Acquire", "I like goals with options on how to get there", "Directing", "Driving", "The bubbling pool, in the depths of which something luminous is swirling", "violin"];
export let hufflepuffResponses = ["The wide, sunny, grassy lane", "Organize", "Drive to defend", "I like a predictable environment", "Supportive", "Amiable", "The fat red toadstools that appear to be talking to each other", "trumpet"];
export let gryffindorResponses = ["The twisting, leaf-strewn path through woods", "Personalize", "Drive to bond", "I like to work with people and have flexibility", "Influencing", "Expressive", "The statue of an old wizard with a strangely twinkling eye", "drum"];
// src: https://cns.utexas.edu/images/CNS/True_Colors_Explanation_Handout_Spring_2016.pdf-
// HP src: https://www.reddit.com/r/Pottermore/comments/44os14/pottermore_sorting_hat_quiz_analysis/